server:
  port: '8089'
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/notification
    username: root
    password: Yubraj@2053
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none

