server:
  port: '8019'
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/notificationcreateDatabaseIfNotExist=true
    username: root
    password: Yubraj@2053
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none

